#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    N = int(input())

    Names = []               # Lista donde será guardado los nombres
    for N_itr in range(N):
        firstNameEmailID = input().split()
        firstName = firstNameEmailID[0]
        emailID = firstNameEmailID[1]
        if re.search('@gmail.com$', emailID):     #si, el nombre tiene anexado @gmail.com "$" es para terminar
            Names.append(firstName)               #ANEXAR el nombre
    print(*sorted (Names), sep='\n')              # Ordenar e imprimir en un nuevo renglon, cada nombre de manera alfabetica

