#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        nk = input().split()

        n = int(nk[0])
        k = int(nk[1])
        
        if (k-1 | k) <= n:                     # Mientras el resultado (OR) no sea mayor a  n, podrá ser el maximo valor k-1
            print ((k-1) & (k-1 | k))
        else:
            print ((k-2) & (k-1 | k-2))       # Al ser mayor el resultado (OR) maximo será k-2
