#!/bin/python3


import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))
    rra = map(str, arr[::-1] )
    print(" ".join(rra))
  
  
  #Using .join and [::-1] instead of a for
